export const methodologiesSeedData = [
    {
        methodologyId: 'REC-v1.2',
        name: 'Renewable Energy Certificates',
        version: '1.2',
        category: 'Renewable Energy',
        description:
            'Carbon credits from renewable energy generation including solar, wind, and hydro projects. Calculates offset based on energy generated and grid emission factor.',
        standard: 'VCS',
        requiredFields: [
            {
                name: 'energyGeneratedMWh',
                type: 'number',
                unit: 'MWh',
                min: 0,
                required: true,
                description: 'Total energy generated in megawatt-hours',
            },
            {
                name: 'gridEmissionFactor',
                type: 'number',
                unit: 'tCO2/MWh',
                default: 0.835,
                required: true,
                description: 'Grid emission factor for the region',
            },
            {
                name: 'projectCapacity',
                type: 'number',
                unit: 'MW',
                required: true,
                description: 'Installed capacity of the renewable energy project',
            },
            {
                name: 'operationalDate',
                type: 'date',
                required: true,
                description: 'Date when project became operational',
            },
        ],
        calculationFormula: 'energyGeneratedMWh * gridEmissionFactor',
        validationRules: [
            {
                field: 'energyGeneratedMWh',
                rule: 'max',
                value: 'projectCapacity * 8760',
                message: 'Energy generated cannot exceed theoretical maximum (capacity × 8760 hours)',
            },
            {
                field: 'gridEmissionFactor',
                rule: 'range',
                min: 0.2,
                max: 1.5,
                message: 'Grid emission factor out of typical range (0.2-1.5 tCO2/MWh)',
            },
        ],
        monitoringRequirements: {
            frequency: 'monthly',
            dataPoints: ['energy_meter_reading', 'weather_data', 'downtime_log'],
            thirdPartyVerification: true,
            reportingFormat: 'VCS MRV Template',
        },
        documentation: {
            guidelines: 'https://verra.org/methodologies/renewable-energy',
            examples: 'https://verra.org/project-examples/renewable-energy',
            calculator: 'https://verra.org/tools/rec-calculator',
        },
        eligibleRegions: ['global'],
        minProjectSize: 1,
        maxProjectSize: null,
        createdBy: 'VCS',
        approvedBy: ['VCS', 'ISO 14064'],
        lastUpdated: new Date('2024-01-15'),
        status: 'active',
        tags: ['renewable', 'energy', 'solar', 'wind', 'hydro'],
        marketDemand: 'high',
        verificationCost: 5000,
        typicalCreditPrice: 15,
    },
    {
        methodologyId: 'REDD-v2.0',
        name: 'REDD+ Reforestation and Forest Conservation',
        version: '2.0',
        category: 'Reforestation',
        description:
            'Carbon credits from reforestation, afforestation, and avoided deforestation projects. Calculates sequestration based on tree planting or forest area protected.',
        standard: 'Gold Standard',
        requiredFields: [
            {
                name: 'hectares',
                type: 'number',
                unit: 'ha',
                min: 0,
                required: true,
                description: 'Total hectares of forest area',
            },
            {
                name: 'sequestrationRate',
                type: 'number',
                unit: 'tCO2/ha/year',
                default: 5.5,
                required: true,
                description: 'Annual carbon sequestration rate per hectare',
            },
            {
                name: 'projectDuration',
                type: 'number',
                unit: 'years',
                min: 1,
                max: 30,
                required: true,
                description: 'Project duration in years',
            },
            {
                name: 'baselineDeforestation',
                type: 'number',
                unit: 'ha/year',
                default: 0,
                required: false,
                description: 'Baseline deforestation rate (for avoided deforestation)',
            },
        ],
        calculationFormula: 'hectares * sequestrationRate * projectDuration',
        validationRules: [
            {
                field: 'sequestrationRate',
                rule: 'range',
                min: 2,
                max: 15,
                message: 'Sequestration rate out of typical range (2-15 tCO2/ha/year)',
            },
            {
                field: 'hectares',
                rule: 'min',
                value: 10,
                message: 'Minimum project size is 10 hectares',
            },
        ],
        monitoringRequirements: {
            frequency: 'annually',
            dataPoints: ['satellite_imagery', 'ground_verification', 'tree_count', 'soil_samples'],
            thirdPartyVerification: true,
            reportingFormat: 'Gold Standard REDD+ Template',
        },
        documentation: {
            guidelines: 'https://www.goldstandard.org/project-developers/redd',
            examples: 'https://www.goldstandard.org/projects/redd-examples',
            pdfUrl: 'https://www.goldstandard.org/redd-methodology.pdf',
        },
        eligibleRegions: ['global'],
        minProjectSize: 55,
        maxProjectSize: null,
        createdBy: 'Gold Standard',
        approvedBy: ['Gold Standard', 'UNFCCC'],
        lastUpdated: new Date('2024-02-01'),
        status: 'active',
        tags: ['forestry', 'reforestation', 'conservation', 'biodiversity'],
        marketDemand: 'high',
        verificationCost: 8000,
        typicalCreditPrice: 20,
    },
    {
        methodologyId: 'OPR-v1.0',
        name: 'Ocean Plastic Removal',
        version: '1.0',
        category: 'Ocean Conservation',
        description:
            'Carbon credits from ocean and river plastic cleanup projects. Calculates offset based on plastic removed and prevented emissions from incineration.',
        standard: 'Plastic Credit Alliance',
        requiredFields: [
            {
                name: 'plasticRemovedKg',
                type: 'number',
                unit: 'kg',
                min: 0,
                required: true,
                description: 'Total plastic removed in kilograms',
            },
            {
                name: 'emissionFactor',
                type: 'number',
                unit: 'tCO2/ton',
                default: 2.7,
                required: true,
                description: 'Emission factor for plastic incineration avoided',
            },
            {
                name: 'disposalMethod',
                type: 'string',
                required: true,
                description: 'Method of plastic disposal (recycling, proper disposal)',
            },
            {
                name: 'collectionDate',
                type: 'date',
                required: true,
                description: 'Date of plastic collection',
            },
        ],
        calculationFormula: '(plasticRemovedKg / 1000) * emissionFactor',
        validationRules: [
            {
                field: 'emissionFactor',
                rule: 'range',
                min: 1.5,
                max: 4.0,
                message: 'Emission factor out of typical range (1.5-4.0 tCO2/ton)',
            },
            {
                field: 'plasticRemovedKg',
                rule: 'min',
                value: 100,
                message: 'Minimum plastic removal is 100 kg',
            },
        ],
        monitoringRequirements: {
            frequency: 'monthly',
            dataPoints: ['weight_receipts', 'disposal_documentation', 'collection_photos', 'gps_data'],
            thirdPartyVerification: true,
            reportingFormat: 'PCA Standard Template',
        },
        documentation: {
            guidelines: 'https://plasticcreditalliance.org/methodology',
            examples: 'https://plasticcreditalliance.org/case-studies',
        },
        eligibleRegions: ['global'],
        minProjectSize: 0.27,
        maxProjectSize: null,
        createdBy: 'Plastic Credit Alliance',
        approvedBy: ['Plastic Credit Alliance'],
        lastUpdated: new Date('2024-03-01'),
        status: 'active',
        tags: ['ocean', 'plastic', 'waste', 'conservation'],
        marketDemand: 'medium',
        verificationCost: 3000,
        typicalCreditPrice: 12,
    },
    {
        methodologyId: 'SCE-v1.1',
        name: 'Soil Carbon Enhancement',
        version: '1.1',
        category: 'Soil Carbon',
        description:
            'Carbon credits from regenerative agriculture and soil carbon sequestration. Calculates offset based on improved farming practices and soil carbon increase.',
        standard: 'Climate Action Reserve',
        requiredFields: [
            {
                name: 'hectares',
                type: 'number',
                unit: 'ha',
                min: 0,
                required: true,
                description: 'Total hectares under regenerative practices',
            },
            {
                name: 'soilCarbonIncrease',
                type: 'number',
                unit: 'tCO2/ha/year',
                default: 2.5,
                required: true,
                description: 'Annual soil carbon increase per hectare',
            },
            {
                name: 'duration',
                type: 'number',
                unit: 'years',
                min: 1,
                max: 20,
                required: true,
                description: 'Duration of regenerative practices',
            },
            {
                name: 'practiceType',
                type: 'string',
                required: true,
                description: 'Type of practice (no-till, cover crops, rotational grazing)',
            },
        ],
        calculationFormula: 'hectares * soilCarbonIncrease * duration',
        validationRules: [
            {
                field: 'soilCarbonIncrease',
                rule: 'range',
                min: 0.5,
                max: 5.0,
                message: 'Soil carbon increase out of typical range (0.5-5.0 tCO2/ha/year)',
            },
            {
                field: 'hectares',
                rule: 'min',
                value: 20,
                message: 'Minimum project size is 20 hectares',
            },
        ],
        monitoringRequirements: {
            frequency: 'annually',
            dataPoints: ['soil_samples', 'farming_practice_logs', 'field_photos', 'yield_data'],
            thirdPartyVerification: true,
            reportingFormat: 'CAR Soil Enrichment Protocol',
        },
        documentation: {
            guidelines: 'https://www.climateactionreserve.org/how/protocols/soil-enrichment/',
            examples: 'https://www.climateactionreserve.org/projects/soil/',
            calculator: 'https://www.climateactionreserve.org/tools/soil-calculator',
        },
        eligibleRegions: ['North America', 'Europe', 'Australia'],
        minProjectSize: 50,
        maxProjectSize: null,
        createdBy: 'Climate Action Reserve',
        approvedBy: ['Climate Action Reserve', 'USDA'],
        lastUpdated: new Date('2024-01-20'),
        status: 'active',
        tags: ['agriculture', 'soil', 'regenerative', 'farming'],
        marketDemand: 'medium',
        verificationCost: 6000,
        typicalCreditPrice: 18,
    },
];
